# Generated by Django 3.0 on 2019-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('publishDate', models.DateField()),
            ],
        ),
    ]
