# Generated by Django 3.0 on 2020-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('status_desc', models.CharField(choices=[('Order Confirmed', 'order confirmed'), ('Order Processing', 'order processing'), ('Shipped', 'shipped'), ('On The Way', 'on the Way'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=16)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
