# Generated by Django 3.0.2 on 2020-01-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Trending', 'Trending'), ('New', 'New'), ('50%', '50%')], default='New', max_length=16),
        ),
    ]
