# Generated by Django 3.0.2 on 2020-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200202_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldPrice',
            field=models.IntegerField(default=0),
        ),
    ]
