# Generated by Django 3.0.2 on 2020-02-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
