# Generated by Django 3.0.2 on 2020-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20200202_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
