# Generated by Django 3.0.4 on 2020-09-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200202_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label_2',
            field=models.CharField(choices=[('Null', 'Null'), ('Trending', 'Trending'), ('New', 'New'), ('50%', '50%'), ('30%', '30%'), ('70%', '70%')], default='Null', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Null', 'Null'), ('Trending', 'Trending'), ('New', 'New'), ('50%', '50%'), ('30%', '30%'), ('70%', '70%')], default='Null', max_length=16),
        ),
    ]
