# Generated by Django 3.0.4 on 2020-09-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_slug_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug_2',
            new_name='sale',
        ),
    ]
