# Generated by Django 3.0.4 on 2020-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200923_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label_2',
        ),
        migrations.AddField(
            model_name='product',
            name='sales_label',
            field=models.CharField(choices=[('Null', 'Null'), ('Trending', 'Trending'), ('New', 'New')], default='Null', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Null', 'Null'), ('Trending', 'Trending'), ('New', 'New')], default='Null', max_length=16),
        ),
    ]
