# Generated by Django 3.0.4 on 2020-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200923_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_label',
            field=models.CharField(choices=[('Null', 'Null'), ('50%', '50%'), ('30%', '30%'), ('70%', '70%')], default='Null', max_length=16),
        ),
    ]
